# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'User_Interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1060, 609)
        self.labelMain = QtWidgets.QLabel(Dialog)
        self.labelMain.setGeometry(QtCore.QRect(0, 0, 1161, 641))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelMain.setFont(font)
        self.labelMain.setText("")
        self.labelMain.setPixmap(QtGui.QPixmap(":/Images/Image/background.jpg"))
        self.labelMain.setScaledContents(True)
        self.labelMain.setObjectName("labelMain")
        self.labelJarvisStart = QtWidgets.QLabel(Dialog)
        self.labelJarvisStart.setGeometry(QtCore.QRect(310, 140, 521, 301))
        self.labelJarvisStart.setText("")
        self.labelJarvisStart.setPixmap(QtGui.QPixmap(":/Images/Image/RoundAnim.gif"))
        self.labelJarvisStart.setScaledContents(True)
        self.labelJarvisStart.setObjectName("labelJarvisStart")
        self.labelSideAnim = QtWidgets.QLabel(Dialog)
        self.labelSideAnim.setGeometry(QtCore.QRect(460, 10, 231, 161))
        self.labelSideAnim.setText("")
        self.labelSideAnim.setPixmap(QtGui.QPixmap(":/Images/Image/SideAnimation.gif"))
        self.labelSideAnim.setScaledContents(True)
        self.labelSideAnim.setObjectName("labelSideAnim")
        self.labelFrame = QtWidgets.QLabel(Dialog)
        self.labelFrame.setGeometry(QtCore.QRect(750, 10, 301, 121))
        self.labelFrame.setText("")
        self.labelFrame.setPixmap(QtGui.QPixmap(":/Images/Image/Frame.jpg"))
        self.labelFrame.setScaledContents(True)
        self.labelFrame.setObjectName("labelFrame")
        self.labelTime = QtWidgets.QLabel(Dialog)
        self.labelTime.setGeometry(QtCore.QRect(840, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(18)
        self.labelTime.setFont(font)
        self.labelTime.setStyleSheet("color: rgb(108, 253, 255);")
        self.labelTime.setObjectName("labelTime")
        self.labelExit = QtWidgets.QLabel(Dialog)
        self.labelExit.setGeometry(QtCore.QRect(540, 490, 71, 61))
        self.labelExit.setText("")
        self.labelExit.setPixmap(QtGui.QPixmap(":/Images/Image/ExitButton.jpg"))
        self.labelExit.setScaledContents(True)
        self.labelExit.setObjectName("labelExit")
        self.pushButtonExit = QtWidgets.QPushButton(Dialog)
        self.pushButtonExit.setGeometry(QtCore.QRect(550, 500, 51, 51))
        self.pushButtonExit.setStyleSheet("background:transparent")
        self.pushButtonExit.setText("")
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.pushButtonStart = QtWidgets.QPushButton(Dialog)
        self.pushButtonStart.setGeometry(QtCore.QRect(490, 230, 171, 131))
        self.pushButtonStart.setStyleSheet("\n"
"image: url(:/Images/Image/StartButtonAnim.gif);\n"
"background:trasparent")
        self.pushButtonStart.setText("")
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 100, 361, 541))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Images/Image/TerminalFram.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.textBrowserConsole = QtWidgets.QTextBrowser(Dialog)
        self.textBrowserConsole.setGeometry(QtCore.QRect(30, 140, 321, 421))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setItalic(True)
        self.textBrowserConsole.setFont(font)
        self.textBrowserConsole.setStyleSheet("color: rgb(0, 255, 255);\n"
"border-radius:none;\n"
"background:transparent")
        self.textBrowserConsole.setObjectName("textBrowserConsole")
        self.labelRam = QtWidgets.QLabel(Dialog)
        self.labelRam.setGeometry(QtCore.QRect(760, 350, 281, 201))
        self.labelRam.setText("")
        self.labelRam.setPixmap(QtGui.QPixmap(":/Images/Image/Ram.gif"))
        self.labelRam.setScaledContents(True)
        self.labelRam.setObjectName("labelRam")
        self.textBrowserRam = QtWidgets.QTextBrowser(Dialog)
        self.textBrowserRam.setGeometry(QtCore.QRect(870, 450, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowserRam.setFont(font)
        self.textBrowserRam.setStyleSheet("color: rgb(0, 255, 255);\n"
"border-radius:none;\n"
"background:transparent")
        self.textBrowserRam.setObjectName("textBrowserRam")
        self.labelR = QtWidgets.QLabel(Dialog)
        self.labelR.setGeometry(QtCore.QRect(876, 410, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelR.setFont(font)
        self.labelR.setStyleSheet("color: rgb(255, 255, 127);\n"
"border-radius:none;\n"
"background:transparent\n"
"")
        self.labelR.setObjectName("labelR")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Assistant"))
        self.labelTime.setText(_translate("Dialog", "12:56:21"))
        self.textBrowserConsole.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:italic;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowserRam.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.labelR.setText(_translate("Dialog", "RAM"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
